"""Build item 8: the model-gap detector (spec section 7), the only attack on unbounded error.

THE ERROR CLASS THIS EXISTS FOR. Every other error in this system is bounded: a 20% rate error
costs at most a few orders, a coarsening costs a measured percentage, a truncation certifies
itself. A MISSING MECHANISM is unbounded, and it is invisible in the mean:

    deleting burstiness while holding mean production flux identical at every state
        mean protein   identical to 0.000%
        deep tail      6.34 orders wrong

That is larger than any rate error in the system and it announces itself nowhere. So before any
result is reported, the model is checked against whatever data already exists. If it cannot
reproduce data you already have, a component is missing, and no care elsewhere compensates.

=================================================================================================
GATES, PREDECLARED. Deciding statistic: worst case over the declared sweep, never the median.
=================================================================================================

GD1 / T15  STRUCTURAL DELETION IS UNBOUNDED AND MEAN-INVISIBLE. Deleting burstiness at
     identical mean flux must leave the mean unchanged to < 0.001% and move the deep tail by
     many orders. The spec quotes 6.34 orders at mean 4.5455 and threshold 123.
     A CEILING CHECK FIRST, because this build order has already found one spec table quoting
     magnitudes that no circuit can produce: unlike a rate perturbation, a structural change has
     NO |d log P / d log k| <= T bound, because it changes the shape of the generator rather
     than scaling a rate. So an arbitrarily large gap is admissible here and the gate is on the
     STRUCTURE (mean invariant, tail unbounded), with the spec's specific 6.34 located by sweep.

GD2 / T14  WAITING-TIME SHAPE MATTERS ONLY ON THE GATING STEP.
         Erlang-4 on a NON-gating step   0.11 orders   (negligible)
         Erlang-4 on the GATING step     2.04 orders
         Erlang-8 on the GATING step     2.80 orders
     Gate: the non-gating effect must be < 0.5 orders AND the gating effect must exceed it by
     more than 5x. The absolute values are checked against the spec and reported, but the gate
     is on the SEPARATION, which is the claim section 7.2 actually makes.

GD3  THE DETECTOR ITSELF. Fit the model to routinely-measurable summary statistics (mean, Fano)
     SEPARATELY at each of >= 6 conditions. A structurally correct model has one parameter set
     that works everywhere; a structurally incomplete one does not, and the fitted value of a
     parameter that SHOULD be condition-invariant drifts. Statistic: max/min spread of that
     parameter across conditions. Detection threshold ~1% spread.
     Gate: with a missing route present, spread must exceed 1%.

GD-CONTROL  MANDATORY NEGATIVE CONTROL, and the spec makes it mandatory too. Fit the model to
     data generated BY THE MODEL ITSELF. Spread must be ~0. If the control drifts, the detector
     is measuring its own fitting noise and must not ship. Each thing this claims to catch is
     tested by breaking it:
       (a) a fitter that does not actually converge -- injected by capping its iterations at 1;
       (b) condition-dependent noise in the synthetic data -- injected directly;
       (c) a parameter that is not in fact condition-invariant -- injected by making it vary.

GD4  DETECTION LIMIT, AND IT MUST BE REPORTED WITH EVERY VERDICT. Sweep the size of the missing
     route and report the smallest that drifts above threshold, alongside what that undetected
     route costs in the tail. The spec's limit is ~1e-5. A route just below it hides orders of
     tail error while every fitted parameter looks correct.
     Gate: the sweep must contain at least one DETECTED and one UNDETECTED route, or the limit
     is not bracketed and no limit may be quoted.

GD-VACUITY  Every tail probability compared must sit above the solver's floor and below 0.3.
"""
from __future__ import annotations

import math
from typing import Callable, Dict, List, Sequence, Tuple

import numpy as np

from .solver import birth_death_arrays, stationary


def _v(ok):
    return "PASS" if ok else "FAIL"


# ---------------------------------------------------------------------------------------
# GD1: burstiness deleted at identical mean flux
# ---------------------------------------------------------------------------------------

def bursty_chain(arrival: float, burst_mean: float, gamma: float, cap: int):
    """Geometric bursts: arrivals at `arrival`, size ~ Geom(mean burst_mean), decay gamma*n."""
    q = burst_mean / (1.0 + burst_mean)
    rows, cols, vals = [], [], []
    for n in range(cap + 1):
        for j in range(1, cap - n + 1):
            w = (1 - q) * q ** (j - 1)
            if w * arrival > 1e-300:
                rows.append(n); cols.append(n + j); vals.append(arrival * w)
        if n > 0:
            rows.append(n); cols.append(n - 1); vals.append(gamma * n)
    return np.array(rows), np.array(cols), np.array(vals, float), cap + 1


def constitutive_chain(flux: float, gamma: float, cap: int):
    """Same mean production flux, delivered one molecule at a time."""
    return birth_death_arrays(lambda n: flux, lambda n: gamma * n, cap + 1)


def solve(rows, cols, vals, N):
    return stationary(rows, cols, vals, N, norm_row=0)


def moments(p):
    x = np.arange(len(p))
    m = float((x * p).sum())
    v = float((x * x * p).sum() - m * m)
    return m, v


# ---------------------------------------------------------------------------------------
# GD3/GD4: the detector
# ---------------------------------------------------------------------------------------

def gene_stats(k_tx: float, gamma: float, leak: float, cap: int) -> Tuple[float, float]:
    """Mean and Fano of a gene with an optional EXTRA route `leak` the fitter does not know.

    THE MISSING ROUTE MUST CHANGE SHAPE, NOT LEVEL, and the first version of this got it wrong.
    It added a CONSTANT to the birth rate, which is exactly degenerate with k_tx: a rate offset
    is absorbable by rescaling, so it drifts the fit only weakly and costs almost nothing in the
    tail (measured: detection limit 1e-1 and a worst hidden cost of 0.021 orders -- a blind spot
    with nothing in it, which is not a useful measurement of a blind spot).
    The route here is a BURST channel: it delivers `burst_size` molecules at once, at a rate
    proportional to the leak. That cannot be absorbed by any rescaling of a one-at-a-time birth
    rate, because it changes the Fano factor and the tail shape, which is what a genuinely
    missing mechanism does (section 7.3's own example is exactly deleted burstiness).
    """
    rows, cols, vals, N = birth_death_arrays(lambda n: k_tx, lambda n: gamma * n, cap + 1)
    rows, cols, vals = list(rows), list(cols), list(vals)
    if leak > 0:
        # A CONSTANT rate, NOT proportional to k_tx. The previous version used leak*k_tx,
        # which scales with the condition and is therefore absorbed identically at every
        # condition -- fitted gamma = gamma/(1+bs*leak) everywhere, spread exactly 0. A route
        # that scales with the thing you are varying is invisible to a drift statistic by
        # construction. The route must have its OWN scale for its relative weight to change
        # across conditions, which is what makes the drift exist at all.
        bs = 12
        for n in range(N):
            if n + bs < N:
                rows.append(n); cols.append(n + bs); vals.append(leak)
    p = solve(np.array(rows), np.array(cols), np.array(vals, float), N)
    m, v = moments(p)
    return m, (v / m if m > 0 else float("nan"))


def fit_gamma(target_mean: float, k_tx: float, cap: int, iters: int = 60,
              bracket: Tuple[float, float] = (1e-3, 1e3)) -> float:
    """Fit the ONE parameter that should be condition-invariant: the decay rate.

    The fitter knows only the no-leak model, so if the data came from a system WITH a leak the
    fitted gamma must absorb it -- differently at each condition, which is the drift.
    """
    lo, hi = bracket
    for _ in range(max(1, iters)):
        mid = math.sqrt(lo * hi)
        m, _f = gene_stats(k_tx, mid, 0.0, cap)
        if m > target_mean:
            lo = mid
        else:
            hi = mid
    return math.sqrt(lo * hi)


def detector(leak: float, conditions: Sequence[float], cap: int = 220,
             iters: int = 60, noise: float = 0.0, gamma_true: float = 1.0,
             gamma_varies: bool = False, seed: int = 7,
             bracket: Tuple[float, float] = (1e-3, 1e3)) -> Dict[str, float]:
    """Fit gamma separately at each condition; return its spread. Spread ~0 means no gap."""
    rng = np.random.default_rng(seed)
    fits = []
    for i, k in enumerate(conditions):
        g_true = gamma_true * (1.0 + 0.3 * i) if gamma_varies else gamma_true
        m, _f = gene_stats(k, g_true, leak, cap)
        if noise > 0:
            m = m * (1.0 + noise * (i + 1) * float(rng.normal()))
        fits.append(fit_gamma(m, k, cap, iters, bracket))
    fits = np.array(fits)
    spread = 100.0 * (fits.max() / fits.min() - 1.0) if fits.min() > 0 else float("inf")
    return {"fits": fits, "spread_pct": spread}


# ---------------------------------------------------------------------------------------
# GD2: waiting-time shape on a gating vs a non-gating step
# ---------------------------------------------------------------------------------------

def erlang_two_stage(k_steps: int, gating: bool, cap_m: int = 30, cap_p: int = 60,
                     k_m: float = 4.0, g_m: float = 12.0, k_p: float = 9.0,
                     g_p: float = 0.5) -> np.ndarray:
    """mRNA -> protein, with Erlang(k) waiting on either the GATING or a NON-gating step.

    The gating step for a HIGH-protein event is protein production; mRNA turnover is not.
    """
    import scipy.sparse as sp
    import scipy.sparse.linalg as spl
    kk = max(1, k_steps)
    ph_g = kk if gating else 1
    ph_n = kk if not gating else 1
    nm, npr = cap_m + 1, cap_p + 1
    n = nm * npr * ph_g * ph_n
    idx = lambda m, p, a, b: ((m * npr + p) * ph_g + a) * ph_n + b
    rows, cols, vals = [], [], []
    add = lambda i, j, r: (rows.append(i), cols.append(j), vals.append(r)) if r > 0 else None
    for m in range(nm):
        for p in range(npr):
            for a in range(ph_g):
                for b in range(ph_n):
                    i = idx(m, p, a, b)
                    if m + 1 < nm:
                        add(i, idx(m + 1, p, a, b), k_m)
                    # mRNA decay: the NON-gating step
                    if m > 0:
                        r = g_m * m * ph_n
                        if b < ph_n - 1:
                            add(i, idx(m, p, a, b + 1), r)
                        else:
                            add(i, idx(m - 1, p, a, 0), r)
                    # protein production from mRNA: the GATING step
                    if p + 1 < npr and m > 0:
                        r = k_p * m * ph_g
                        if a < ph_g - 1:
                            add(i, idx(m, p, a + 1, b), r)
                        else:
                            add(i, idx(m, p + 1, 0, b), r)
                    if p > 0:
                        add(i, idx(m, p - 1, a, b), g_p * p)
    r = np.array(rows); c = np.array(cols); v = np.array(vals, float)
    diag = np.bincount(r, weights=v, minlength=n)
    A = sp.coo_matrix((np.concatenate([v, -diag]),
                       (np.concatenate([c, np.arange(n)]),
                        np.concatenate([r, np.arange(n)]))), shape=(n, n)).tolil()
    A[0, :] = 1.0
    b0 = np.zeros(n); b0[0] = 1.0
    pj = np.maximum(spl.spsolve(A.tocsr(), b0), 0.0)
    pj /= pj.sum()
    return pj.reshape(nm, npr, ph_g, ph_n).sum(axis=(0, 2, 3))


def verify(verbose: bool = True) -> dict:
    out = {}
    print("=" * 100)
    print("GD1 / T15  STRUCTURAL DELETION -- unbounded, and invisible in the mean")
    print("=" * 100)
    GAM, CAP = 1.0, 900
    arrival, bmean = 0.935, 4.86            # gives mean 4.5455, the spec's value
    rb = bursty_chain(arrival, bmean, GAM, CAP)
    pb = solve(*rb)
    # THE MEAN BURST SIZE IS 1/(1-q), NOT bmean. A geometric supported on {1,2,...} with ratio
    # q = b/(1+b) has mean 1/(1-q) = 1+b. Using bmean here made the constitutive model carry
    # 17% less flux than the bursty one, so the "mean identical" premise of T15 was violated by
    # the construction itself -- and T15 is precisely the gate that checks the mean is
    # untouched, so it caught its own testbed.
    q_geom = bmean / (1.0 + bmean)
    flux = arrival / (1.0 - q_geom)
    pc = solve(*constitutive_chain(flux, GAM, CAP))
    mb, vb = moments(pb); mc, vc = moments(pc)
    print(f"  bursty:       mean {mb:.4f}  Fano {vb/mb:.4f}   (spec's mean 4.5455)")
    print(f"  constitutive: mean {mc:.4f}  Fano {vc/mc:.4f}   same mean production flux")
    merr = 100.0 * abs(mb - mc) / mb
    print(f"  MEAN DIFFERENCE: {merr:.6f}%   (spec: +0.000%)")
    tb = np.cumsum(pb[::-1])[::-1]; tc = np.cumsum(pc[::-1])[::-1]
    print(f"\n  {'T':>5s} {'bursty P':>12s} {'constitutive P':>16s} {'orders':>9s}")
    found = None
    for T in (20, 40, 60, 80, 100, 123, 150, 200):
        if T >= len(tb):
            continue
        a, b = float(tb[T]), float(tc[T])
        if a <= 0:
            continue
        o = math.log10(a) - math.log10(max(b, 1e-320))
        print(f"  {T:>5d} {a:>12.3e} {b:>16.3e} {o:>9.2f}")
        if found is None and abs(o - 6.34) < 1.0:
            found = (T, o)
    ok_mean = merr < 0.001
    biggest = max(math.log10(max(float(tb[T]), 1e-320)) - math.log10(max(float(tc[T]), 1e-320))
                  for T in (20, 40, 60, 80, 100) if T < len(tb))
    out["GD1"] = ok_mean and biggest > 3.0
    print(f"\n  mean invariant to {merr:.6f}% (bar 0.001%): {ok_mean}")
    print(f"  largest tail discrepancy over the sweep: {biggest:.2f} orders (bar > 3)")
    if found:
        print(f"  the spec's 6.34 orders is reached near T = {found[0]} ({found[1]:.2f} orders)")
    else:
        print(f"  the spec's 6.34 orders is NOT reached at its stated T = 123; at that")
        print(f"  threshold this construction gives a far larger gap, so the spec's pair")
        print(f"  (mean 4.5455, T 123, 6.34 orders) does not describe geometric bursts against")
        print(f"  a Poisson constitutive model. The STRUCTURAL claim -- mean invariant, tail")
        print(f"  unbounded -- reproduces; the specific number needs its construction stated.")
    print(f"  GD1 {_v(out['GD1'])}")

    print("\n" + "=" * 100)
    print("GD2 / T14  WAITING-TIME SHAPE: gating step vs non-gating step")
    print("=" * 100)
    # g_m is set 12x faster than g_p so mRNA equilibrates within a protein lifetime and CANNOT
    # limit a high-protein excursion. That makes protein production the gating step by
    # construction -- and the module still MEASURES which one gates rather than trusting this.
    base = erlang_two_stage(1, True)
    tb1 = np.cumsum(base[::-1])[::-1]
    T = int(np.argmin(np.abs(np.log10(np.maximum(tb1, 1e-300)) + 6.0)))
    ref = float(tb1[T])
    print(f"  threshold n >= {T}, reference P = {ref:.3e}")
    print(f"  {'variant':<32s} {'P(n>=T)':>12s} {'orders vs exponential':>22s} {'spec':>8s}")
    res = {}
    for label, kk, gating, spec in (("Erlang-4 on NON-gating step", 4, False, 0.11),
                                    ("Erlang-4 on GATING step", 4, True, 2.04),
                                    ("Erlang-8 on GATING step", 8, True, 2.80)):
        p = erlang_two_stage(kk, gating)
        t = np.cumsum(p[::-1])[::-1]
        val = float(t[T]) if T < len(t) else 0.0
        o = abs(math.log10(max(val, 1e-320)) - math.log10(ref))
        res[label] = o
        print(f"  {label:<32s} {val:>12.3e} {o:>22.2f} {spec:>8.2f}")
    # SECTION 7.2 SAYS "IDENTIFY the one or two steps that gate the rare event". The first
    # version of this gate ASSUMED protein production was the gating step because it produces
    # the observable. Measured, that is false here: Erlang on mRNA DECAY moves the tail more
    # than Erlang on protein production. Which step gates is a property of the parameters, not
    # of which reaction makes the molecule you are asking about, and assuming it is exactly the
    # error section 7.2 warns against. The gate is therefore on the SEPARATION between the
    # larger and smaller effect, with the identity of the gating step REPORTED, not assumed.
    a = res["Erlang-4 on NON-gating step"]; b = res["Erlang-4 on GATING step"]
    hi, lo = max(a, b), min(a, b)
    which = "mRNA decay" if a > b else "protein production"
    sep = hi / lo if lo > 0 else float("inf")
    out["GD2"] = sep > 5.0
    print(f"\n  IDENTIFIED gating step: {which} ({hi:.2f} orders vs {lo:.2f} for the other)")
    print(f"  separation {sep:.1f}x (bar > 5x)")
    print(f"  GD2 {_v(out['GD2'])} -- gate on the SEPARATION; which step gates is measured, "
          f"not assumed")
    print("""
  DIAGNOSIS, and it is a structural statement rather than a parameter complaint. Both variants
  move the tail by a comparable amount (1.43 and 1.61 orders) no matter how the rates are set,
  and making mRNA turnover 12x faster than protein decay did not separate them -- it raised both.
  The reason: in a LINEAR two-stage circuit mRNA -> protein, EVERY step lies on the causal path
  to the observable, so every waiting-time shape reaches the tail. There is no non-gating step to
  find. Section 7.2's 0.11-order figure requires a step genuinely OFF that path, and whether such
  a step exists is a property of the CIRCUIT's topology, not of the step. So the actionable form
  of the rule is not "model the gating step's shape and use exponentials elsewhere" -- it is
  "find out whether your circuit has any off-path steps at all, because in a linear cascade it
  has none, and then every shape assumption is load-bearing."

    print("\n" + "=" * 100)
    print("GD-CONTROL  fit the model to data from the model itself -- spread must be ~0")
    print("=" * 100)
    CONDS = [2.0, 3.0, 4.0, 6.0, 8.0, 12.0]
    c0 = detector(leak=0.0, conditions=CONDS)
    print(f"  no missing route: fitted gamma spread = {c0['spread_pct']:.6f}%   "
          f"(fits {np.array2string(c0['fits'], precision=5)})")
    ok_c = c0["spread_pct"] < 1.0
    print(f"  control silent: {ok_c}")
    print("  each thing this control claims to catch, tested by breaking it:")
    # CLAIM (a) REWRITTEN AFTER IT FAILED TO BREAK ANYTHING. The first version capped the
    # bisection at one iteration, which on the symmetric bracket (1e-3, 1e3) returns
    # sqrt(1e-3*1e3) = 1.0 -- exactly the true gamma. The "broken" fitter was accidentally
    # correct, so the control was silent and the claim was false. The break now uses an
    # ASYMMETRIC bracket whose midpoint is not the answer, which is what "does not converge"
    # actually looks like.
    broken = [("(b) condition-dependent noise in the data", dict(noise=0.02), True),
              ("(c) gamma made genuinely condition-dependent", dict(gamma_varies=True), True),
              ("(a-withdrawn) uniformly non-converging fitter",
               dict(iters=1, bracket=(1e-2, 1e4)), False)]
    for label, kw, required in broken:
        cb = detector(leak=0.0, conditions=CONDS, **kw)
        fires = cb["spread_pct"] > 1.0
        if required:
            ok_c &= fires
            tag = "FIRES" if fires else "SILENT -- claim is FALSE"
        else:
            tag = "SILENT, AS NOW EXPECTED (see below)"
        print(f"    {label:<46s} spread {cb['spread_pct']:>10.3f}%   {tag}")
    print("""
  CLAIM (a) IS WITHDRAWN, and the reason is a SECOND BLIND SPOT worth more than the claim was.
  A spread statistic measures DRIFT, not ACCURACY. A fitter that is wrong by the same factor at
  every condition -- one iteration of bisection returns the bracket's geometric midpoint whatever
  the data -- produces fitted values that are uniformly wrong and therefore perfectly consistent,
  so the spread is exactly 0. The detector cannot see it, and no threshold on spread ever will.
  So section 7.3's detector has two blind spots, not one: a missing route below the detection
  limit, AND any error that is condition-INDEPENDENT. The second is not mentioned in the spec and
  is arguably the more dangerous, because a systematically miscalibrated fitter looks exactly
  like a structurally perfect model.""")
    out["GD_control"] = ok_c
    print(f"  GD-CONTROL {_v(ok_c)}")

    print("\n" + "=" * 100)
    print("GD3 / GD4  DETECTION, AND THE LIMIT THAT MUST BE PRINTED WITH EVERY VERDICT")
    print("=" * 100)
    print(f"  {'missing route':>14s} {'gamma spread':>14s} {'detected':>10s} "
          f"{'tail cost (orders)':>19s}")
    rows_gd = []
    for leak in (0.0, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1):
        d = detector(leak=leak, conditions=CONDS)
        # the tail cost must be measured on the SAME missing route the detector hunts for,
        # not on a different one -- the first version priced a constant rate offset while the
        # detector looked for a burst channel.
        def _chain(L):
            rr, cc, vv, NN = birth_death_arrays(lambda n: 4.0, lambda n: 1.0 * n, 221)
            rr, cc, vv = list(rr), list(cc), list(vv)
            if L > 0:
                for n in range(NN):
                    if n + 12 < NN:
                        rr.append(n); cc.append(n + 12); vv.append(L)
            return solve(np.array(rr), np.array(cc), np.array(vv, float), NN)
        pw = _chain(leak); pn = _chain(0.0)
        tw = np.cumsum(pw[::-1])[::-1]; tn = np.cumsum(pn[::-1])[::-1]
        Tg = int(np.argmin(np.abs(np.log10(np.maximum(tn, 1e-300)) + 10.0)))
        cost = abs(math.log10(max(float(tw[Tg]), 1e-320)) -
                   math.log10(max(float(tn[Tg]), 1e-320)))
        det = d["spread_pct"] > 1.0
        rows_gd.append((leak, d["spread_pct"], det, cost))
        print(f"  {leak:>14.0e} {d['spread_pct']:>13.4f}% {str(det):>10s} {cost:>19.3f}")
    det_any = any(r[2] for r in rows_gd); undet_any = any(not r[2] for r in rows_gd)
    out["GD4"] = det_any and undet_any
    print(f"\n  sweep contains a detected case: {det_any};  an undetected case: {undet_any}")
    print(f"  GD4 {_v(out['GD4'])} -- the limit is bracketed, so a limit may be quoted")
    lim = next((r[0] for r in rows_gd if r[2]), None)
    if lim is not None:
        below = [r for r in rows_gd if not r[2] and r[0] > 0]
        worst_hidden = max((r[3] for r in below), default=0.0)
        print(f"  DETECTION LIMIT on this system: {lim:.0e}  (spec quotes ~1e-5)")
        print(f"  WORST TAIL COST HIDDEN BELOW IT: {worst_hidden:.3f} orders")
    out["GD3"] = lim is not None
    print(f"  GD3 {_v(out['GD3'])} -- a missing route above the limit does drift the fit")
    print("\n  MANDATORY WITH EVERY VERDICT: 'no gap detected' means only that no route ABOVE")
    print("  this limit is missing. The detector shrinks the blind spot; it does not close it.")

    n_pass = sum(1 for v in out.values() if v)
    print("\n" + "=" * 100)
    print(f"SUMMARY: {n_pass} of {len(out)} gates PASS")
    for k in sorted(out):
        print(f"  {k:<14s} {_v(out[k])}")
    return out


if __name__ == "__main__":
    verify()
