"""ALGORITHM 2 -- REM-VE side-chain / rotamer packing, with a GUARANTEED global optimum.

This is REM's sharpest claim in docking. Every production packer (Rosetta's simulated
annealing, SCWRL's tree decomposition with heuristics, Monte Carlo repacking) returns a good
answer with no certificate. Bucket elimination returns THE optimum over d^n rotamer
assignments in d^treewidth time, and the treewidth of an interface contact graph is small
because residues only couple when they are spatially close.

    n interface residues, d rotamers each  ->  d^n assignments
    cost = d^treewidth, and treewidth is bounded by interface geometry, not by n

WHAT MAKES THE COMPARISON HONEST. A guaranteed optimum is only interesting if the baseline
it beats is a fair one, so the greedy baseline here is not a straw man: it is best-of-N
random restarts with full pairwise context and iterative improvement to convergence, which
is what a naive-but-competent packer does. The reported gap is against that, and the gap is
measured per case rather than asserted.

ROTAMERS. No external rotamer library is available offline, so rotamers are generated by
rotating each side chain about its own chi1/chi2 torsions in fixed increments from the
deposited conformation. That is a real discretisation of the true side-chain freedom and it
keeps the native conformation in the set (offset 0), which matters: a library that cannot
represent the answer would make every method look equally bad and hide the search quality
being measured.
"""
from __future__ import annotations

import itertools
import time
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from rem.factorgraph import FactorGraph
from rem.docking.data import Structure, _canonical_ids
from rem.docking.score import CUTOFF, charges, lj_params, pair_energy

BACKBONE_SET = {"N", "CA", "C", "O", "OXT"}

# chi1 rotation axis (CA->CB) moves everything beyond CB; chi2 (CB->CG) everything beyond CG.
CHI_AXES = (("CA", "CB"), ("CB", "CG"))


def _rotate(coords: np.ndarray, p0: np.ndarray, p1: np.ndarray, angle: float) -> np.ndarray:
    """Rodrigues rotation of `coords` about the axis p0->p1 by `angle` radians."""
    ax = p1 - p0
    n = np.linalg.norm(ax)
    if n < 1e-8:
        return coords
    k = ax / n
    v = coords - p0
    return (v * np.cos(angle)
            + np.cross(k, v) * np.sin(angle)
            + k[None, :] * (v @ k)[:, None] * (1 - np.cos(angle))) + p0


def residue_rotamers(s: Structure, res_key: str, n_chi1: int = 6,
                     n_chi2: int = 3) -> List[np.ndarray]:
    """Side-chain coordinate sets for one residue: the native plus torsion rotations.

    Offset 0 is ALWAYS the deposited conformation, so the native is representable."""
    ids = _canonical_ids(s)
    sel = ids == res_key
    names = s.atom_names[sel]
    xyz = s.coords[sel]
    side = ~np.isin(names, list(BACKBONE_SET))
    if side.sum() == 0:
        return [xyz.copy()]
    pos = {str(a): i for i, a in enumerate(names)}
    out = [xyz.copy()]
    for ai, (a0, a1) in enumerate(CHI_AXES):
        if a0 not in pos or a1 not in pos:
            break
        p0, p1 = xyz[pos[a0]], xyz[pos[a1]]
        # atoms strictly beyond the axis' second atom move with the torsion
        beyond = side & ~np.isin(names, [a0, a1])
        if ai == 1:
            beyond &= ~np.isin(names, ["CB"])
        if beyond.sum() == 0:
            continue
        nsteps = n_chi1 if ai == 0 else n_chi2
        base = list(out)
        out = []
        for conf in base:
            for k in range(nsteps):
                c = conf.copy()
                if k:
                    c[beyond] = _rotate(c[beyond], p0, p1, 2 * np.pi * k / nsteps)
                out.append(c)
    # de-duplicate identical conformations (small side chains generate repeats)
    uniq, seen = [], set()
    for c in out:
        key = np.round(c, 3).tobytes()
        if key not in seen:
            seen.add(key); uniq.append(c)
    return uniq


class RepackProblem:
    """Interface residues, their rotamers, and the pairwise energies coupling them."""

    def __init__(self, mobile: Structure, fixed: Structure, res_keys: Sequence[str],
                 n_chi1: int = 6, n_chi2: int = 3, cutoff: float = CUTOFF):
        self.mobile, self.fixed = mobile, fixed
        self.res_keys = list(res_keys)
        self.cutoff = cutoff
        ids = _canonical_ids(mobile)
        self.rot: Dict[str, List[np.ndarray]] = {}
        self.meta: Dict[str, dict] = {}
        for rk in self.res_keys:
            sel = ids == rk
            self.rot[rk] = residue_rotamers(mobile, rk, n_chi1, n_chi2)
            self.meta[rk] = {
                "names": mobile.atom_names[sel], "elements": mobile.elements[sel],
                "res_names": mobile.res_names[sel],
                "side": ~np.isin(mobile.atom_names[sel], list(BACKBONE_SET)),
            }
        # everything not being repacked is background: the partner plus the mobile backbone
        # and the non-interface residues of the mobile chain.
        bg = ~np.isin(ids, self.res_keys)
        self.bg = Structure(mobile.coords[bg], mobile.atom_names[bg], mobile.res_ids[bg],
                            mobile.res_names[bg], mobile.elements[bg])

    # ------------------------------------------------------------------ energies
    def _side(self, rk: str, k: int):
        m = self.meta[rk]
        c = self.rot[rk][k][m["side"]]
        return c, m["elements"][m["side"]], charges(m["res_names"][m["side"]],
                                                    m["names"][m["side"]])

    def unary(self, rk: str, k: int) -> float:
        """Rotamer against everything fixed: the partner, the backbone, the background."""
        c, e, q = self._side(rk, k)
        tot = 0.0
        for other in (self.fixed, self.bg):
            if len(other):
                tot += pair_energy(c, e, q, other.coords, other.elements,
                                   charges(other.res_names, other.atom_names),
                                   self.cutoff)["total"]
        return tot

    def pairwise(self, ra: str, ka: int, rb: str, kb: int) -> float:
        ca, ea, qa = self._side(ra, ka)
        cb, eb, qb = self._side(rb, kb)
        return pair_energy(ca, ea, qa, cb, eb, qb, self.cutoff)["total"]

    def contact_graph(self) -> List[Tuple[str, str]]:
        """Residue pairs whose rotamer clouds can reach each other. This sparsity IS the
        treewidth bound, so it is computed geometrically rather than assumed."""
        edges = []
        for a, b in itertools.combinations(self.res_keys, 2):
            ca = np.vstack([self.rot[a][k][self.meta[a]["side"]]
                            for k in range(len(self.rot[a]))])
            cb = np.vstack([self.rot[b][k][self.meta[b]["side"]]
                            for k in range(len(self.rot[b]))])
            if len(ca) and len(cb):
                d = np.sqrt(((ca[:, None, :] - cb[None, :, :]) ** 2).sum(-1)).min()
                if d < self.cutoff:
                    edges.append((a, b))
        return edges

    def to_factorgraph(self) -> Tuple[FactorGraph, List[Tuple[str, str]]]:
        g = FactorGraph()
        for rk in self.res_keys:
            g.add_var(rk, len(self.rot[rk]))
            g.add_factor([rk], np.array([self.unary(rk, k)
                                         for k in range(len(self.rot[rk]))]))
        edges = self.contact_graph()
        for a, b in edges:
            tab = np.array([[self.pairwise(a, ka, b, kb) for kb in range(len(self.rot[b]))]
                            for ka in range(len(self.rot[a]))])
            g.add_factor([a, b], tab)
        return g, edges

    # ------------------------------------------------------------------ solvers
    def energy_of(self, assign: Dict[str, int], g: FactorGraph) -> float:
        return float(sum(f.table[tuple(assign[v] for v in f.vars)] for f in g.factors))

    def solve_exact(self, g: Optional[FactorGraph] = None):
        if g is None:
            g, _ = self.to_factorgraph()
        t = time.perf_counter()
        val, arg, info = g.eliminate("min")
        return {"energy": val, "assignment": arg, "treewidth": info["treewidth"],
                "largest_table": info["largest_table"], "seconds": time.perf_counter() - t,
                "n_configs": float(np.prod([len(self.rot[r]) for r in self.res_keys]))}

    def solve_greedy(self, g: FactorGraph, restarts: int = 20, seed: int = 0):
        """Best-of-N random restarts with iterative improvement to convergence.

        Deliberately NOT a straw man: each restart sees full pairwise context and improves
        every residue against its neighbours until nothing changes. A guaranteed optimum is
        only worth reporting against a baseline that is trying."""
        rng = np.random.default_rng(seed)
        t = time.perf_counter()
        best, best_a = np.inf, None
        for _ in range(restarts):
            a = {r: int(rng.integers(len(self.rot[r]))) for r in self.res_keys}
            for _sweep in range(50):
                changed = False
                for r in self.res_keys:
                    cur = a[r]
                    costs = []
                    for k in range(len(self.rot[r])):
                        a[r] = k
                        costs.append(self.energy_of(a, g))
                    a[r] = int(np.argmin(costs))
                    if a[r] != cur:
                        changed = True
                if not changed:
                    break
            e = self.energy_of(a, g)
            if e < best:
                best, best_a = e, dict(a)
        return {"energy": best, "assignment": best_a, "restarts": restarts,
                "seconds": time.perf_counter() - t}


def build_from_case(case: Dict[str, Structure], side: str = "r", bound: bool = True,
                    max_residues: int = 8, cutoff: float = CUTOFF,
                    n_chi1: int = 6, n_chi2: int = 3) -> RepackProblem:
    """Interface repacking problem from a DB5 case, on the real deposited coordinates."""
    from rem.docking.data import interface_residues
    tag = "b" if bound else "u"
    mob = case[f"{side}_{tag}"]
    fix = case[f"{'l' if side == 'r' else 'r'}_{tag}"]
    keys = interface_residues(mob, fix, cutoff=6.0)
    # keep the residues with the most side-chain freedom -- packing GLY/ALA proves nothing
    scored = []
    for k in keys:
        n = len(residue_rotamers(mob, k, n_chi1, n_chi2))
        if n > 1:
            scored.append((n, k))
    scored.sort(reverse=True)
    return RepackProblem(mob, fix, [k for _, k in scored[:max_residues]],
                         n_chi1, n_chi2, cutoff)


def verify(case_id: str = "1A2K", max_residues: int = 6, n_chi1: int = 3,
           n_chi2: int = 2, verbose: bool = True) -> dict:
    """Elimination optimum vs EXHAUSTIVE ENUMERATION over all rotamer assignments.

    The reference is a different algorithm -- an explicit product over every assignment,
    scoring each from the same factor tables -- so agreement is not circular. It is run on a
    REAL interface from a real structure, not a synthetic graph, because the claim being
    checked is about interface geometry producing low treewidth."""
    from rem.docking.data import load_case
    # Enumeration is the reference, so the instance must be enumerable. Defaults give
    # 6 rotamers x 6 residues = 46,656 assignments -- small enough to enumerate, large
    # enough that a wrong elimination would not agree by luck.
    prob = build_from_case(load_case(case_id), max_residues=max_residues,
                           n_chi1=n_chi1, n_chi2=n_chi2)
    g, edges = prob.to_factorgraph()
    ex = prob.solve_exact(g)
    names = prob.res_keys
    t = time.perf_counter()
    best, best_a = np.inf, None
    for combo in itertools.product(*[range(len(prob.rot[r])) for r in names]):
        a = dict(zip(names, combo))
        e = prob.energy_of(a, g)
        if e < best:
            best, best_a = e, a
    brute_s = time.perf_counter() - t
    err = abs(ex["energy"] - best)
    # the returned assignment must actually achieve the returned energy
    consist = abs(prob.energy_of(ex["assignment"], g) - ex["energy"])
    gr = prob.solve_greedy(g, restarts=20)
    if verbose:
        print(f"  rem.docking.repack.verify   case {case_id}, {len(names)} interface residues")
        print(f"    rotamers per residue: {[len(prob.rot[r]) for r in names]}")
        print(f"    configurations {ex['n_configs']:.3e}   contact edges {len(edges)}"
              f"   treewidth {ex['treewidth']}")
        print(f"    elimination  {ex['energy']:12.5f} kcal/mol   {ex['seconds']*1000:8.1f} ms")
        print(f"    enumeration  {best:12.5f} kcal/mol   {brute_s*1000:8.1f} ms")
        print(f"    max |elimination - enumeration|          {err:.3e}")
        print(f"    max |E(argmin) - reported|               {consist:.3e}")
        print(f"    greedy best-of-20 restarts {gr['energy']:12.5f}   "
              f"gap {gr['energy']-ex['energy']:+.5f} kcal/mol")
    return {"case": case_id, "err_vs_enumeration": err, "argmin_consistency": consist,
            "exact": ex["energy"], "greedy": gr["energy"],
            "gap": gr["energy"] - ex["energy"], "treewidth": ex["treewidth"],
            "n_configs": ex["n_configs"], "elim_ms": ex["seconds"] * 1000,
            "brute_ms": brute_s * 1000, "n_residues": len(names), "n_edges": len(edges)}
