"""Bioelectric Vmem estimator — Phase B1 observable.

Computes a Goldman-Hodgkin-Katz (GHK) membrane voltage from existing
intracellular ion counts in `state.metabolite_counts`, using
literature reference values for extracellular concentrations and
permeability ratios. This is a derived observable; it does not
modify simulator state.

The GHK equation (only K+, Na+, Cl- — the three monovalent ions
relevant to bacterial Vmem):

    V_m = (RT/F) * ln( ( P_K [K+]_o + P_Na [Na+]_o + P_Cl [Cl-]_i )
                       / ( P_K [K+]_i + P_Na [Na+]_i + P_Cl [Cl-]_o ) )

with concentrations in M, permeabilities dimensionless ratios, and
the result in volts. We multiply by 1000 to report millivolts.

Caveats (read these before using the result anywhere)
-----------------------------------------------------

1. **Syn3A's medium has K+ nearly equal inside (10 mM) and outside
   (12.67 mM)**, unlike typical bacteria that have a strong K+
   gradient. The Luthey-Schulten Syn3A reference media is engineered
   to be minimal; published data are at
   ``cell_sim/data/Minimal_Cell_ComplexFormation/input_data/initial_concentrations.xlsx``,
   sheets "Simulation Medium" and "Intracellular Metabolites". As a
   result, V_m at the simulator's resting state is small (single-
   digit positive mV) rather than the canonical bacterial −100 to
   −180 mV. This is a feature of JCVI-Syn3A's design, not a bug. Any
   detector using V_m as an essentiality feature should not assume a
   canonical bacterial baseline.

2. **Permeability ratios are placeholders.** The Syn3A genome has no
   measured ion-channel permeabilities. Defaults below come from
   B. subtilis-like bacterial values (P_K = 1, P_Na = 0.04, P_Cl =
   0.45). These are reasonable order-of-magnitude bacterial defaults
   but they are NOT measured for Syn3A. A future Phase B2 / B3 effort
   would either fit them from simulator outputs or absorb them into
   a calibrated detector.

3. **The intracellular Cl- concentration in Luthey-Schulten Syn3A is
   zero.** This is because Cl- is not in the "Intracellular
   Metabolites" sheet of the Luthey-Schulten initial concentrations
   data; the simulator initializes [Cl-]_i = 0. With P_Cl > 0 and
   [Cl-]_i = 0, the GHK denominator can blow up. The estimator
   handles this by clamping [Cl-]_i to a small floor (1e-6 mM) and
   reducing P_Cl's contribution accordingly. If a future Syn3A model
   adds a real Cl- intracellular value, the floor becomes irrelevant.

4. **No proton motive force (PMF) contribution.** Real bacterial Vmem
   is dominated by the PMF generated by the F1F0 H+ ATPase. The
   Luthey-Schulten Syn3A model holds H+ counts at a sentinel infinity
   and does not track an explicit H+ gradient. Adding PMF as a Vmem
   driver is Phase B2 (dynamics) work; Phase B1 reports the
   GHK-from-K+/Na+/Cl- estimate without PMF.

5. **This estimator is deterministic given state.** No RNG is used;
   bit-identity at flag-off is preserved trivially because the
   estimator is only called when the flag is on, and even when called
   it does not write to state.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping, Optional


# ============================================================================
# Physical constants
# ============================================================================
R_GAS = 8.314          # J / (mol K)
F_FARADAY = 96485.0    # C / mol
DEFAULT_TEMPERATURE_K = 310.15  # 37 C


# ============================================================================
# Defaults sourced from cell_sim/data/.../initial_concentrations.xlsx
# (Luthey-Schulten Syn3A reference values, 2022)
# ============================================================================
DEFAULT_REFERENCE_EXTRACELLULAR_MM: Mapping[str, float] = {
    "M_k_e": 12.67,
    "M_na1_e": 19.38,
    "M_cl_e": 19.90,
}

# Bacterial-typical permeability ratios. See module docstring caveat.
DEFAULT_PERMEABILITY: Mapping[str, float] = {
    "K": 1.00,
    "Na": 0.04,
    "Cl": 0.45,
}

_INTRACELLULAR_CL_FLOOR_MM = 1e-6


@dataclass(frozen=True)
class BioelectricEstimatorConfig:
    """All knobs the Vmem estimator reads. Defaults match the Phase B1
    placeholders. Overriding any of these is fine; the estimator stays
    deterministic given state."""

    temperature_K: float = DEFAULT_TEMPERATURE_K
    permeability: Mapping[str, float] = field(
        default_factory=lambda: dict(DEFAULT_PERMEABILITY)
    )
    reference_extracellular_mM: Mapping[str, float] = field(
        default_factory=lambda: dict(DEFAULT_REFERENCE_EXTRACELLULAR_MM)
    )
    intracellular_cl_floor_mM: float = _INTRACELLULAR_CL_FLOOR_MM


# ============================================================================
# Helpers
# ============================================================================
def _count_to_mM(count: float, volume_L: float) -> float:
    """Match the order of operations in
    ``cell_sim.layer3_reactions.coupled.count_to_mM`` for bit-identity.
    See that function's docstring for why parens matter."""
    AVOGADRO = 6.022e23
    if volume_L <= 0:
        return 0.0
    return (count / AVOGADRO) / volume_L * 1000.0


def nernst_potential_mv(
    conc_inside_mM: float,
    conc_outside_mM: float,
    charge: int = +1,
    temperature_K: float = DEFAULT_TEMPERATURE_K,
) -> float:
    """Single-ion Nernst potential in millivolts.

    E_ion = (RT / zF) * ln([ion]_o / [ion]_i)

    Returns 0.0 if either concentration is non-positive (defensive
    against zero-count states; the GHK estimator handles ion-by-ion
    fallback separately).
    """
    if conc_inside_mM <= 0 or conc_outside_mM <= 0 or charge == 0:
        return 0.0
    import math
    rt_over_zf_volts = R_GAS * temperature_K / (charge * F_FARADAY)
    e_volts = rt_over_zf_volts * math.log(conc_outside_mM / conc_inside_mM)
    return e_volts * 1000.0


# ============================================================================
# Estimator
# ============================================================================
def estimate_vmem_mv(
    state,
    config: Optional[BioelectricEstimatorConfig] = None,
) -> float:
    """Return the GHK-derived membrane voltage in millivolts.

    Reads ``state.metabolite_counts`` for intracellular ion counts and
    ``state.metabolite_volume_L`` for the cell volume. Extracellular
    concentrations come from ``config.reference_extracellular_mM``
    (Phase B1: literature reference values, NOT the simulator's
    sentinel-infinity external pools).

    Returns ``float('nan')`` if cell volume is missing or zero, or if
    the metabolite_counts dict is missing entirely. Both are non-fatal:
    a NaN VMEM_MV in the trajectory snapshot is a clear "not computed"
    signal that downstream detectors can filter on.
    """
    if config is None:
        config = BioelectricEstimatorConfig()

    mc = getattr(state, "metabolite_counts", None)
    if mc is None:
        return float("nan")
    vol = float(getattr(state, "metabolite_volume_L", 0.0) or 0.0)
    if vol <= 0:
        return float("nan")

    # Intracellular concentrations (mM) from the same count_to_mM order
    # of operations the rest of the simulator uses.
    k_in = _count_to_mM(float(mc.get("M_k_c", 0)), vol)
    na_in = _count_to_mM(float(mc.get("M_na1_c", 0)), vol)
    cl_in_raw = _count_to_mM(float(mc.get("M_cl_c", 0)), vol)
    cl_in = max(cl_in_raw, config.intracellular_cl_floor_mM)

    # Extracellular reference concentrations (mM)
    k_out = float(config.reference_extracellular_mM.get("M_k_e", 0.0))
    na_out = float(config.reference_extracellular_mM.get("M_na1_e", 0.0))
    cl_out = float(config.reference_extracellular_mM.get("M_cl_e", 0.0))

    p_k = float(config.permeability.get("K", 0.0))
    p_na = float(config.permeability.get("Na", 0.0))
    p_cl = float(config.permeability.get("Cl", 0.0))

    # GHK numerator: P_K [K]_o + P_Na [Na]_o + P_Cl [Cl]_i
    # GHK denominator: P_K [K]_i + P_Na [Na]_i + P_Cl [Cl]_o
    num = p_k * k_out + p_na * na_out + p_cl * cl_in
    den = p_k * k_in + p_na * na_in + p_cl * cl_out

    if num <= 0 or den <= 0:
        return float("nan")

    import math
    rt_over_f_volts = R_GAS * config.temperature_K / F_FARADAY
    v_volts = rt_over_f_volts * math.log(num / den)
    return v_volts * 1000.0


__all__ = [
    "BioelectricEstimatorConfig",
    "DEFAULT_PERMEABILITY",
    "DEFAULT_REFERENCE_EXTRACELLULAR_MM",
    "estimate_vmem_mv",
    "nernst_potential_mv",
]
