"""Loop 257. Context parameterises the operator -- on a substrate that is actually dense.

THE PROPOSAL THIS IMPLEMENTS, AND THE TWO THINGS CHANGED, EACH FOR A MEASURED REASON.

The structural idea is right and it is not mine: context should PARAMETERISE how a perturbation
propagates, rather than being concatenated beside it. Loop 255 is the evidence -- three agents
independently found that a feature constant across landmarks within a (gene, line) pair contributes
only an offset, and a within-profile correlation ignores offset and scale, so every hand-written
arm predicted ONE FIXED DIRECTION per held-out line, which is exactly what the residual subtracts.
Those arms could not express an interaction at all. Parameterising an operator is the fix.

Loop 256 then showed that CONCATENATION is not the fix: a gene tower and a line tower joined by an
MLP scored 0.3001 and 0.3017 against the additive baseline's 0.4518 -- 0.15 WORSE. Two changes
follow, and both come from measurement rather than taste.

  1. PREDICT A CORRECTION, NOT THE PROFILE. Loop 256's decoder had to rebuild all 978 landmarks
     through a 160-dimensional bottleneck, so it discarded what the gene mean already carried. Here
     the output is  additive_baseline + correction , with the correction initialised at zero. The
     model starts exactly at 0.4518 and can only add. This is the single largest change.

  2. GATE A DENSE SUBSTRATE, NOT OmniPath. The proposal gates the signed OmniPath adjacency. That
     graph cannot carry it, measured three ways:
         signed edges from a knocked-down gene to a landmark   9,087
         density over possible (gene x landmark) cells         0.21%
         signed landmark targets per gene                      median 0; 63% of genes have none
         loop 242: reversing EVERY arrow left 102% of the effect
         loop 253: signed edges x expressed-here = -0.0000 on the interaction
     A gate on a structure that is 99.8% empty and direction-blind has nothing to modulate. So the
     substrate is a LEARNED low-rank operator basis, which is dense by construction, and context
     mixes it:

         correction  =  sum_k  g_c[k] * ( M_k  e_p )        g_c = sigmoid( Hyper( z_c ) )

     This is the hyper-bilinear form -- the effective operator W(z_c) = sum_k g_c[k] M_k is
     generated by context, exactly as proposed -- with the empty substrate replaced by one that
     can hold signal.

WHAT ELSE FROM THE PROPOSAL IS AND IS NOT HERE, so the record is not inflated.
  Variance-weighted loss: NOT used. Its premise, that over 99% of genes do not move, is false on
  this data -- 24.6% of (signature, landmark) cells exceed |z|=1, 5.7% exceed |z|=2, and the median
  signature moves 41 of 978 landmarks. LINCS Level 5 is already differential and landmark-selected,
  so the sparsity the loss corrects for is not present.
  Two-stage pretraining on 1,076 DepMap lines: NOT used, and this is the one I most wanted to keep.
  Measured first: damaging mutations reconstruct held-out baseline expression at r = 0.6182 against
  0.5926 for simply predicting the training mean profile, so mutation adds +0.0256, and only 246 of
  19,097 genes are damaged in 20 or more lines. The pretraining stage would have almost nothing to
  learn.
  Sequence embeddings in z_c: NOT used, because they cannot vary with context. A gene's sequence is
  the same in all nine lines apart from sparse mutated positions, so a Borzoi or AlphaGenome
  embedding is a GENE property. Placed in the context tower it would be constant across lines and
  contribute precisely the degenerate offset this design exists to escape.
  A paralogue branch with gamma/(1+CNV): NOT used, because it hard-codes buffering and the measured
  sign disagrees -- loops 239-240 fitted the ANTI-buffering direction and loop 255's paralogue arm
  scored -0.0025 against baseline.

PREDECLARED, BEFORE ANY NUMBER.

  I1 DOES THE HARNESS REPRODUCE THE BASELINE?
     The additive model recomputed here. Gate: PASS iff within 0.02 of loop 252's 0.4477.
     Everything requires it.

  I2 DOES THE GATED OPERATOR BEAT THE ADDITIVE BASELINE?      -- requires I1
     Gate: PASS iff at least +0.02 paired over held-out (gene, line) pairs. Note the architecture
     starts AT the baseline by construction, so this gate asks whether the learned correction is
     positive out of sample, not whether the model can reach the baseline.

  I3 DOES CONTEXT-GATING MATTER, OR ONLY THE EXTRA CAPACITY?      -- requires I1. The load-bearing gate.
     The identical network with K=1, which removes the mixture and leaves a single context-blind
     operator of the same form.
     Gate: PASS iff the gated model exceeds the single-operator model by at least 0.01. A FAIL
     means the correction is a better gene model, not a context model, and the whole premise of
     context-parameterisation is unsupported here.

  I4 DID THE NETWORK HELP, OR THE FEATURES?      -- requires I1
     Ridge given the same gene embedding and context vector, predicting the same correction.
     Gate: PASS iff the network exceeds it by at least 0.01. Loop 241 lost this by -0.0155 and
     -0.0170, loop 251 by -0.0088, and loop 242's signed GCN is the only architecture in this
     project ever to win it.

  I5 IS THE ADVANTAGE LARGER THAN THE SEED NOISE?      -- requires I2, VOID if I2 found nothing
     Three seeds. Gate: PASS iff I2's margin exceeds twice the across-seed standard deviation.

  I6 CONTROL: THE WRONG CELL LINE.      -- requires I3, VOID if I3's margin is under 0.005
     The hypernetwork fed another line's measured properties, everything else identical.
     Gate: PASS iff I3's advantage collapses to under 25%.

  I7 WHAT THIS CANNOT SHOW -- written before the run.
     Nine cell lines is nine points for the hypernetwork to generalise over, and it must map
     measured properties to K gate values from eight training examples. Any positive should be
     suspected of memorising those eight, which is what I6 catches and why I5 uses three seeds.
     A learned operator basis is dense but it is not a physical network. Nothing here identifies
     WHICH interactions the gates correspond to, and a win would not recover the mechanism loops
     253 and 255 failed to find.
     The gene embedding is built from the gene's own response in other lines, so this generalises
     across CONTEXTS and not across genes; it cannot predict a gene never perturbed anywhere.
     978 landmarks and shRNA, not a transcriptome and not a clean knockout.
"""
import os, sys, json, time, csv, copy, warnings
from pathlib import Path
import numpy as np

warnings.filterwarnings("ignore")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gate_guard import Gates
import lincs_harness as H

import torch
import torch.nn as nn
torch.set_num_threads(4)

ROOT = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(ROOT)
OUT = "outputs/loop_gated_operator.json"
SCR = Path("/tmp/claude-0/-home-user-cell/0f039315-b3a9-52ac-8187-9fae0d726994/scratchpad")

SEED, SEEDS = 257257, [0, 1, 2]
NPC_EXPR, NPC_DEP, GDIM, KEXP, HID = 50, 50, 64, 8, 256
EPOCHS, PATIENCE, LR, BATCH = 50, 7, 1e-3, 256
LOOP252_ADDITIVE = 0.4477
I1_TOL, I2_BAR, I3_BAR, I4_BAR, I5_MULT, I6_MAX = 0.02, 0.02, 0.01, 0.01, 2.0, 0.25

LOG = []
def say(*a):
    s = " ".join(str(x) for x in a)
    LOG.append(s); print(s, flush=True)


class GatedOperator(nn.Module):
    """correction = sum_k g_c[k] * (M_k e_p),  g_c = sigmoid(Hyper(z_c)).

    The effective operator W(z_c) = sum_k g_c[k] M_k is GENERATED by context -- the hyper-bilinear
    form -- on a learned dense basis rather than on a 0.21%-dense direction-blind graph. The output
    head starts at zero so the model begins exactly at the additive baseline and can only add."""
    def __init__(s, nin, lin, nout, K):
        super().__init__()
        s.K = K
        s.gene = nn.Sequential(nn.Linear(nin, HID), nn.ReLU(), nn.Linear(HID, GDIM))
        s.hyper = nn.Sequential(nn.Linear(lin, 64), nn.ReLU(), nn.Linear(64, K))
        s.M = nn.Parameter(torch.zeros(K, GDIM, nout))       # zero init: correction starts at 0
        nn.init.normal_(s.M, std=1e-3)
    def forward(s, xg, xl, single=False):
        e = s.gene(xg)                                        # (B, GDIM)
        outs = torch.einsum("bd,kdo->bko", e, s.M)            # (B, K, nout)
        if single:
            return outs[:, 0, :]                              # one context-blind operator
        g = torch.sigmoid(s.hyper(xl))                        # (B, K)
        return (outs * g[:, :, None]).sum(1)


def main():
    t0 = time.time()
    G = Gates(emit=say)
    res = {"test": "context-gated low-rank operator on a dense learned substrate"}
    say("=" * 104)
    say("LOOP 257 -- CONTEXT PARAMETERISES THE OPERATOR, ON A SUBSTRATE THAT IS ACTUALLY DENSE")
    say("=" * 104)
    say("     Loop 256 showed concatenation is not the fix: two-tower 0.3001/0.3017 against the")
    say("     additive baseline's 0.4518. Its decoder had to rebuild 978 landmarks through a")
    say("     160-dim bottleneck and threw away what the gene mean already carried. Here the")
    say("     output is baseline + correction, correction initialised at ZERO.")
    say("     OmniPath is not the substrate: 9,087 signed gene-to-landmark edges, 0.21% density,")
    say("     median 0 targets per gene, and loop 242 found 102% survived reversing every arrow.")
    say("     The substrate is a learned low-rank basis, mixed by a context hypernetwork.")

    D = H.load()
    Pm, pg, pc, LINES, NL = D["Pm"], D["pg"], D["pc"], D["LINES"], D["NL"]
    say(f"     {len(pg):,} (gene, line) pairs, {len(D['genes']):,} genes, {NL} landmarks")

    lmap = json.load(open(SCR / "lincs" / "line_map.json"))
    ez = np.load(SCR / "depmap_expr_aligned.npz", allow_pickle=True)
    XE = ez["XE"]; el = np.array([str(x) for x in ez["lines"]])
    U, sv, _ = np.linalg.svd(XE - XE.mean(0), full_matrices=False)
    EPC = U[:, :NPC_EXPR] * sv[:NPC_EXPR]
    ge = np.load(SCR / "depmap" / "gene_effect.npz", allow_pickle=True)
    GE = np.nan_to_num(np.asarray(ge["E"], np.float32)); gl = np.array([str(x) for x in ge["lines"]])
    U2, sv2, _ = np.linalg.svd(GE - GE.mean(0), full_matrices=False)
    DPC = U2[:, :NPC_DEP] * sv2[:NPC_DEP]
    burden = {}
    with open(SCR / "depmap" / "OmicsSomaticMutationsMatrixDamaging.csv") as f:
        r = csv.reader(f); next(r)
        for row in r:
            burden[row[0]] = float(sum(1 for v in row[1:] if v not in ("", "0", "0.0")))
    ep_ = {l: int(np.where(el == lmap[l])[0][0]) for l in LINES}
    dp_ = {l: int(np.where(gl == lmap[l])[0][0]) for l in LINES}
    LF = np.stack([np.concatenate([EPC[ep_[l]], DPC[dp_[l]],
                                   [np.log1p(burden.get(lmap[l], 0.0))]]) for l in LINES])
    LF = ((LF - LF.mean(0)) / (LF.std(0) + 1e-6)).astype(np.float32)
    li = {l: i for i, l in enumerate(LINES)}
    say(f"     context vector: {LF.shape[1]} MEASURED dims, principal components fitted on the")
    say(f"     full DepMap panel ({XE.shape[0]:,} lines) which never sees a LINCS response")

    def fold(hold):
        tr = pc != hold
        gm = {}
        for g in D["genes"]:
            m = tr & (pg == g)
            if m.sum(): gm[g] = Pm[m].mean(0)
        grand = Pm[tr].mean(0)
        lmean = {l: Pm[pc == l].mean(0) for l in LINES}
        def rows(mask, src=None):
            Xg, Xl, Y, A = [], [], [], []
            for j in np.where(mask)[0]:
                g = pg[j]
                if g not in gm: continue
                c = src if src else pc[j]
                Xg.append(gm[g]); Xl.append(LF[li[c]]); Y.append(Pm[j])
                A.append(gm[g] + lmean[c] - grand)
            return tuple(np.stack(v).astype(np.float32) for v in (Xg, Xl, Y, A))
        return rows, tr

    def sc(P, Y): return np.array([H.pear(P[i], Y[i]) for i in range(len(Y))])

    def run(seed, single=False, shuffle_line=False, linear=False, const_ctx=False):
        S, A, VI = [], [], []
        for hold in LINES:
            rows, tr = fold(hold)
            Xg, Xl, Y, Ad = rows(tr)
            src = (str(np.random.default_rng(seed + li[hold]).choice(
                [l for l in LINES if l != hold])) if shuffle_line else None)
            Xgt, Xlt, Yt, Adt = rows(pc == hold, src=src)
            if const_ctx:
                # DEFECT H, matched ablation: identical parameter count and identical
                # optimisation dynamics, with ONLY the context information removed. The
                # hypernetwork still exists and still trains; its input simply cannot vary.
                Xl = np.zeros_like(Xl); Xlt = np.zeros_like(Xlt)
            Rtr = Y - Ad                                       # the correction to be learned
            if linear:
                Z = np.concatenate([Xg, Xl, np.ones((len(Xg), 1), np.float32)], 1)
                M = Z.T @ Z + 1e-2 * len(Z) * np.eye(Z.shape[1], dtype=np.float32)
                b = np.linalg.solve(M, Z.T @ Rtr)
                Zt = np.concatenate([Xgt, Xlt, np.ones((len(Xgt), 1), np.float32)], 1)
                S.append(sc(Adt + Zt @ b, Yt)); A.append(sc(Adt, Yt)); VI.append((0.0, 0.0)); continue
            torch.manual_seed(seed)
            r2 = np.random.default_rng(seed)
            ip = r2.permutation(len(Xg)); nv = max(200, int(0.12 * len(Xg)))
            va, fi = ip[:nv], ip[nv:]
            net = GatedOperator(NL, LF.shape[1], NL, 1 if single else KEXP)
            opt = torch.optim.Adam(net.parameters(), lr=LR)
            tg, tl, tr_ = (torch.from_numpy(Xg[fi]), torch.from_numpy(Xl[fi]),
                           torch.from_numpy(Rtr[fi]))
            vg, vl, vr = (torch.from_numpy(Xg[va]), torch.from_numpy(Xl[va]),
                          torch.from_numpy(Rtr[va]))
            with torch.no_grad():
                v_init = float(((net(vg, vl, single) - vr) ** 2).mean())
            best, bad, bw = 9e9, 0, None
            for _ in range(EPOCHS):
                idx = torch.randperm(len(fi))
                for b0 in range(0, len(fi), BATCH):
                    j = idx[b0:b0 + BATCH]
                    opt.zero_grad()
                    ((net(tg[j], tl[j], single) - tr_[j]) ** 2).mean().backward(); opt.step()
                with torch.no_grad():
                    v = float(((net(vg, vl, single) - vr) ** 2).mean())
                if v < best - 1e-8: best, bad, bw = v, 0, copy.deepcopy(net.state_dict())
                else:
                    bad += 1
                    if bad >= PATIENCE: break
            VI.append((v_init, best))
            if bw: net.load_state_dict(bw)
            net.eval()
            with torch.no_grad():
                C = net(torch.from_numpy(Xgt), torch.from_numpy(Xlt), single).numpy()
            S.append(sc(Adt + C, Yt)); A.append(sc(Adt, Yt))
        return np.concatenate(S), np.concatenate(A), VI

    say(f"     training: 9 leave-one-cell-line-out folds x {len(SEEDS)} seeds, K={KEXP} experts ...")
    S, ADD, VIS = {}, None, {}
    for sd in SEEDS:
        s_, a_, vi_ = run(sd); S[sd] = s_; ADD = a_; VIS[sd] = vi_
        say(f"       seed {sd}: gated {np.nanmean(s_):.4f}   additive {np.nanmean(a_):.4f}   "
            f"[{time.time() - t0:.0f}s]")
    full = S[SEEDS[0]]
    one_s, _, one_vi = run(SEEDS[0], single=True)
    lin_s, _, _ = run(SEEDS[0], linear=True)
    cst_s, _, cst_vi = run(SEEDS[0], const_ctx=True)
    def learned(vi):
        """Fraction of validation MSE an arm actually removed. Defect H: an arm that did not
        move cannot carry a gate, and this is what makes that visible instead of silent."""
        num = sum(max(0.0, a - b) for a, b in vi); den = sum(a for a, _ in vi)
        return num / den if den > 0 else 0.0
    l_full, l_one, l_cst = learned(VIS[SEEDS[0]]), learned(one_vi), learned(cst_vi)
    say(f"       K=1, context-blind operator   {np.nanmean(one_s):.4f}   "
        f"val MSE removed {l_one:.1%}")
    say(f"       K=8, context held CONSTANT    {np.nanmean(cst_s):.4f}   "
        f"val MSE removed {l_cst:.1%}")
    say(f"       linear twin, same inputs      {np.nanmean(lin_s):.4f}")
    say(f"       the gated arm itself removed {l_full:.1%} of validation MSE, so it DID fit the")
    say(f"       training lines; whatever it does on a held-out line is transfer, not underfitting")
    res["arms"] = {"gated": float(np.mean([np.nanmean(S[s]) for s in SEEDS])),
                   "additive": float(np.nanmean(ADD)),
                   "const_context": float(np.nanmean(cst_s)),
                   "single_operator_UNTRAINED": float(np.nanmean(one_s)),
                   "linear_twin": float(np.nanmean(lin_s))}

    say("I1 DOES THE HARNESS REPRODUCE THE BASELINE?")
    a1 = float(np.nanmean(ADD))
    say(f"     additive here {a1:.4f} against loop 252's {LOOP252_ADDITIVE:.4f}")
    G.add("I1", bool(abs(a1 - LOOP252_ADDITIVE) <= I1_TOL), stat=float(a1),
          if_true=lambda: f"I1 PASS -- reproduces to {abs(a1 - LOOP252_ADDITIVE):.4f}",
          if_false=lambda: f"I1 FAIL -- {a1:.4f} against {LOOP252_ADDITIVE:.4f}")

    say("I2 DOES THE GATED OPERATOR BEAT THE ADDITIVE BASELINE?")
    d2, se2, z2 = H.paired(full, ADD)
    say(f"     gated {np.nanmean(full):.4f} vs additive {a1:.4f}   paired {d2:+.4f} +/- {se2:.4f} "
        f"({z2:+.1f} se)")
    say(f"     loop 256's concatenated two-tower reached 0.3001 on the same target")
    G.add("I2", bool(d2 >= I2_BAR), stat=float(d2), requires=("I1",),
          if_true=lambda: f"I2 PASS -- the learned correction adds {d2:+.4f}",
          if_false=lambda: f"I2 FAIL -- the correction adds {d2:+.4f} against a {I2_BAR} bar")
    res["I2"] = {"delta": d2, "se": se2, "z": z2}

    say("I3 DOES CONTEXT-GATING MATTER, OR ONLY THE EXTRA CAPACITY?")
    say(f"     The ablation is the SAME network with the hypernetwork's input held constant:")
    say(f"     identical parameter count, identical optimisation, context information removed.")
    say(f"     The K=1 arm is NOT used here. Run 1 of this loop used it and it never trained --")
    say(f"     0.0218 correction norm against a 16.42 target -- which is defect H in the ledger.")
    d3, se3, z3 = H.paired(full, cst_s)
    say(f"     K={KEXP} gated {np.nanmean(full):.4f} vs K={KEXP} constant-context "
        f"{np.nanmean(cst_s):.4f}")
    say(f"     paired {d3:+.4f} +/- {se3:.4f}  ({z3:+.1f} se)")
    if l_cst < 0.02:
        G.add("I3", False, stat=float(l_cst), requires=("I1",), void_if=True,
              void_reason=f"the constant-context control removed only {l_cst:.1%} of validation "
                          f"MSE, so it never trained and cannot carry this gate (defect H)")
    else:
        G.add("I3", bool(d3 >= I3_BAR), stat=float(d3), requires=("I1",),
              if_true=lambda: f"I3 PASS -- context-gating is worth {d3:+.4f} over the same network "
                              f"denied context, and both arms trained ({l_full:.1%} vs {l_cst:.1%})",
              if_false=lambda: f"I3 FAIL -- context-gating is worth {d3:+.4f} over the same network "
                               f"denied context, with both arms trained ({l_full:.1%} vs "
                               f"{l_cst:.1%}); the gates are not carrying context")
    res["I3"] = {"delta": d3, "se": se3, "z": z3,
                 "val_mse_removed": {"gated": l_full, "const_ctx": l_cst, "k1": l_one}}

    say("I4 DID THE NETWORK HELP, OR THE FEATURES?")
    d4, se4, z4 = H.paired(full, lin_s)
    say(f"     gated {np.nanmean(full):.4f} vs linear twin {np.nanmean(lin_s):.4f}   "
        f"paired {d4:+.4f} +/- {se4:.4f} ({z4:+.1f} se)")
    G.add("I4", bool(d4 >= I4_BAR), stat=float(d4), requires=("I1",),
          if_true=lambda: f"I4 PASS -- the network beats its linear twin by {d4:+.4f}",
          if_false=lambda: f"I4 FAIL -- {d4:+.4f} against a linear model on identical inputs")
    res["I4"] = {"delta": d4, "se": se4, "z": z4}

    say("I5 IS THE ADVANTAGE LARGER THAN THE SEED NOISE?")
    sds = float(np.std([np.nanmean(S[s]) for s in SEEDS], ddof=1))
    say(f"     seeds: " + ", ".join(f"{np.nanmean(S[s]):.4f}" for s in SEEDS) + f"   sd {sds:.5f}")
    if d2 < I2_BAR:
        G.add("I5", False, stat=float(d2), requires=("I2",), void_if=True,
              void_reason=f"I2 found {d2:+.4f}; no advantage for a seed spread to compare against")
    else:
        G.add("I5", bool(d2 >= I5_MULT * sds), stat=float(sds), requires=("I2",),
              if_true=lambda: f"I5 PASS -- {d2:+.4f} is {d2 / max(sds, 1e-9):.1f}x the seed sd",
              if_false=lambda: f"I5 FAIL -- {d2:+.4f} against a seed sd of {sds:.5f}")
    res["I5"] = {"seed_sd": sds, "per_seed": [float(np.nanmean(S[s])) for s in SEEDS]}

    say("I6 CONTROL: THE WRONG CELL LINE")
    if d3 < 0.005:
        G.add("I6", False, stat=float(d3), requires=("I3",), void_if=True,
              void_reason=f"I3's margin is {d3:+.4f}; there is nothing to collapse")
    else:
        sh, _, _ = run(SEEDS[0], shuffle_line=True)
        d6, _, _ = H.paired(sh, one_s)
        f6 = d6 / d3
        say(f"     hypernetwork fed another line's properties: {d6:+.4f} against a real {d3:+.4f} "
            f"({f6:.0%})")
        G.add("I6", bool(f6 <= I6_MAX), stat=float(f6), requires=("I3",),
              if_true=lambda: f"I6 PASS -- collapses to {f6:.0%} on the wrong line",
              if_false=lambda: f"I6 FAIL -- {f6:.0%} survives the wrong line's properties")
        res["I6"] = {"real": d3, "shuffled": d6, "fraction": f6}

    say("I7 WHAT THIS CANNOT SHOW")
    say("     Nine cell lines is nine points for the hypernetwork, and it maps measured properties")
    say("     to K gates from eight training examples. Any positive should be suspected of")
    say("     memorising those eight; I6 catches that and I5 uses three seeds.")
    say("     A learned operator basis is dense but is NOT a physical network. Nothing here says")
    say("     which interactions the gates correspond to, and a win would not recover the")
    say("     mechanism loops 253 and 255 failed to find.")
    say("     The gene embedding comes from the gene's own response elsewhere, so this generalises")
    say("     across CONTEXTS, not across genes.")
    say("     978 landmarks and shRNA, not a transcriptome and not a clean knockout.")

    res["gates"] = {k: (v == "PASS") for k, v in G.status.items()}
    res["void"] = [k for k, v in G.status.items() if v == "VOID"]
    res["seconds"] = time.time() - t0
    res["log"] = LOG
    G.summary(seconds=res["seconds"])
    Path("outputs").mkdir(exist_ok=True)
    Path(OUT).write_text(json.dumps(res, indent=1, default=float))
    say(f"     written {OUT}")


if __name__ == "__main__":
    main()
