"""Generate build_complete_cell.ipynb — a Colab notebook that ACTUALLY runs all three models
and fetches every data source they need, writes the three enrichment files the builder consumes,
then assembles + serves the complete interactive cell.

  Model 1  our integrated model      -> trains on features (+DepMap truth) -> predicted_essentiality.csv
  Model 2  atlas / scGPT cell-type   -> CELLxGENE census (Tabula Sapiens)   -> celltype_masters.json (+expression)
  Model 3  Geneformer                -> in-silico perturbation (delete)     -> gf_perturb.json

Run: python colab/make_cell_notebook.py"""
import json
from pathlib import Path
def md(*t): return {"cell_type":"markdown","metadata":{},"source":[l if l.endswith("\n") else l+"\n" for l in t]}
def code(*t): return {"cell_type":"code","metadata":{},"execution_count":None,"outputs":[],"source":[l if l.endswith("\n") else l+"\n" for l in t]}
BR="claude/vectorize-gex-propensity-NRqBW"
cells=[
md("# Build the complete cell — all three models, all the data",
   "This notebook genuinely **runs all three models** and **fetches every data source**, writes what each model",
   "produces into the cell, then assembles and serves the interactive result.",
   "",
   "| model | runs here | data it fetches | file it writes | how the cell uses it |",
   "|---|---|---|---|---|",
   "| **1. our integrated model** | trains a classifier on our 14-layer features + DepMap truth | DepMap CRISPRGeneEffect, repo features | `predicted_essentiality.csv` | fills essentiality for genes with no CRISPR label |",
   "| **2. atlas / scGPT cell-type** | per-cell-type expression from the human atlas | CELLxGENE census (Tabula Sapiens) | `celltype_masters.json`, `celltype_expression.csv` | data-driven master TFs → cell-type active networks |",
   "| **3. Geneformer** | in-silico *delete* perturbation | Geneformer weights (HF) + tokenized atlas cells | `gf_perturb.json` | enriches the knockout cascade with predicted downstream genes |",
   "",
   "**Runtime:** set *Runtime → A100* (Model 2 census + Model 3 Geneformer want a GPU and ~15–40 min).",
   "Each model cell is guarded — if one environment isn't available the notebook still completes and builds a cell,",
   "but on a proper GPU+internet runtime **all three run for real.** See `docs/CELL_ARCHITECTURE.md`."),

code("# [1] repo (scripts + pre-processed network/compartment/HIV data) ",
   "import os, sys, json",
   "if not os.path.exists('colab/build_cell_complete.py'):",
   f"    !git clone -q --branch {BR} https://github.com/nikku03/cell.git",
   "    os.chdir('cell')",
   "print('cwd:', os.getcwd())",
   "IN_COLAB='google.colab' in sys.modules"),
code("# [2] installs",
   "!pip -q install torch scikit-learn pandas numpy scipy anndata",
   "!pip -q install cellxgene-census            # Model 2 (atlas)",
   "!pip -q install git+https://huggingface.co/ctheodoris/Geneformer 2>/dev/null || echo 'Geneformer install skipped'  # Model 3",
   "OUT='outputs/orphan'; os.makedirs(OUT, exist_ok=True)"),
code("# [3] (optional) persist to Drive",
   "PROJ=None",
   "if IN_COLAB:",
   "    try:",
   "        from google.colab import drive; drive.mount('/content/drive')",
   "        PROJ='/content/drive/MyDrive/cell_model'; os.makedirs(PROJ, exist_ok=True)",
   "    except Exception as e: print('no Drive:', e)",
   "print('persist ->', PROJ or 'local only')"),

md("## Model 1 — our integrated essentiality model\n"
   "Trains on our 14-layer features with **measured DepMap essentiality** as truth, then predicts the "
   "unlabeled genes. Baseline to match: features-only AUC ~0.97. Output → `predicted_essentiality.csv`."),
code("import pandas as pd, numpy as np",
   "bb=pd.read_csv(f'{OUT}/integrated_cell_human.csv')",
   "print('backbone genes:', len(bb))",
   "# --- fetch DepMap measured essentiality (truth). Update the figshare file id from depmap.org/portal/download ---",
   "DEPMAP_URL=os.environ.get('DEPMAP_URL','')  # e.g. a CRISPRGeneEffect.csv figshare direct link",
   "dep=None",
   "if DEPMAP_URL:",
   "    try:",
   "        d=pd.read_csv(DEPMAP_URL, index_col=0)      # cell lines x genes (Chronos)",
   "        frac_dep=(d< -0.5).mean(axis=0)             # fraction of lines where gene is essential",
   "        frac_dep.index=[g.split(' ')[0] for g in frac_dep.index]",
   "        dep=pd.Series(frac_dep.groupby(level=0).max())",
   "        print('DepMap genes:', len(dep))",
   "    except Exception as e: print('DepMap fetch failed, using repo labels:', e)",
   "else: print('set DEPMAP_URL env for extra truth; using repo essential labels')"),
code("from sklearn.ensemble import GradientBoostingClassifier",
   "from sklearn.model_selection import cross_val_predict",
   "from sklearn.metrics import roc_auc_score",
   "FEATS=['loeuf','is_tf','regulon_out','regulators_in','ppi_degree','n_pathways','cpg_promoter','enhancers','n_diseases']",
   "X=bb.copy()",
   "for c in ['regulon_out','regulators_in','ppi_degree','n_pathways','enhancers','n_diseases']: X[c]=np.log1p(X[c].fillna(0))",
   "X['loeuf']=X['loeuf'].fillna(X['loeuf'].median()); X[FEATS]=X[FEATS].fillna(0)",
   "y=bb['essential'].copy()",
   "if dep is not None:                              # merge DepMap truth where we have it",
   "    m=bb['gene'].map(lambda g: dep.get(g, np.nan))",
   "    y=y.where(y.notna(), (m>0.5).astype(float).where(m.notna()))",
   "lab=y.notna().values",
   "clf=GradientBoostingClassifier(max_depth=3,n_estimators=300,learning_rate=0.05)",
   "cvp=cross_val_predict(clf,X.loc[lab,FEATS],y[lab],cv=5,method='predict_proba')[:,1]",
   "print('Model 1 CV AUC:', round(roc_auc_score(y[lab],cvp),3),'| labeled:',int(lab.sum()))",
   "clf.fit(X.loc[lab,FEATS],y[lab])",
   "prob=clf.predict_proba(X[FEATS])[:,1]",
   "pred=pd.DataFrame({'gene':bb['gene'],'pred':(prob>0.5).astype(int),'prob':prob.round(3)})",
   "pred=pred[y.isna().values]                       # only the genes with NO measured label",
   "pred.to_csv(f'{OUT}/predicted_essentiality.csv',index=False)",
   "print('Model 1 -> predicted_essentiality.csv for', len(pred),'unlabeled genes;', int(pred.pred.sum()),'predicted essential')"),

md("## Model 2 — atlas / scGPT cell-type layer (Tabula Sapiens via CELLxGENE census)\n"
   "Pulls per-cell-type mean expression across the human atlas, then for each cell type finds its **master TFs** "
   "= transcription factors most *specific* to that type (mean-expr in type ÷ mean across types). "
   "Subsamples cells first to avoid OOM. Output → `celltype_masters.json`, `celltype_expression.csv`."),
code("import cellxgene_census, anndata as ad, scipy.sparse as sp, traceback",
   "TFset=set(bb.loc[bb.is_tf==1,'gene'])",
   "adata=None; cell_means=None",
   "TISSUES=['blood','liver','heart','lung','brain','kidney']  # tissue_general controlled vocab",
   "PER_TYPE=150; MAX_CELLS=30000                              # keep memory + time sane",
   "try:",
   "    with cellxgene_census.open_soma(census_version='stable') as census:",
   "        VF=\"is_primary_data==True and tissue_general in \"+repr(TISSUES)",
   "        # metadata only first (cheap), then subsample coords -> fetch just those cells",
   "        obs=cellxgene_census.get_obs(census,'Homo sapiens',value_filter=VF,",
   "                                     column_names=['soma_joinid','cell_type'])",
   "        obs=pd.DataFrame(obs)",
   "        ids=(obs.groupby('cell_type',group_keys=False)",
   "                .apply(lambda d:d.sample(min(len(d),PER_TYPE),random_state=0)))",
   "        if len(ids)>MAX_CELLS: ids=ids.sample(MAX_CELLS,random_state=0)",
   "        print('subsampled cells:',len(ids),'across',ids.cell_type.nunique(),'cell types')",
   "        adata=cellxgene_census.get_anndata(census,'Homo sapiens',    # no var filter (avoids schema issues)",
   "               obs_coords=sorted(ids['soma_joinid'].tolist()),",
   "               obs_column_names=['cell_type'])",
   "    # per-cell-type mean of CP10k-normalized expression, computed SPARSELY (no dense NxG blowup)",
   "    X=adata.X.tocsr() if sp.issparse(adata.X) else sp.csr_matrix(adata.X)",
   "    lib=np.asarray(X.sum(1)).ravel(); lib[lib==0]=1",
   "    Xn=X.multiply(1e4/lib[:,None]).tocsr()",
   "    cts=adata.obs['cell_type'].astype(str).values",
   "    uc=pd.unique(cts); ci={c:i for i,c in enumerate(uc)}",
   "    rows=np.array([ci[c] for c in cts])",
   "    Ind=sp.csr_matrix((np.ones(len(rows)),(rows,np.arange(len(rows)))),shape=(len(uc),len(rows)))",
   "    counts=np.asarray(Ind.sum(1)).ravel()",
   "    means=np.log1p(np.asarray((Ind@Xn).todense())/counts[:,None])",
   "    genes=adata.var['feature_name'].astype(str).values",
   "    cell_means=pd.DataFrame(means,index=uc,columns=genes)",
   "    cell_means=cell_means.loc[:,~cell_means.columns.duplicated()]",
   "    cell_means.to_csv(f'{OUT}/celltype_expression.csv')",
   "    print('cell-type expression:',cell_means.shape)",
   "except Exception:",
   "    traceback.print_exc(); print('Model 2 census unavailable -> curated masters fallback')"),
code("masters={}",
   "if cell_means is not None:",
   "    glob=cell_means.mean(axis=0)+1e-6",
   "    spec=cell_means.div(glob,axis=1)              # specificity per cell type",
   "    for ct in cell_means.index:",
   "        tfs=[g for g in spec.columns if g in TFset]",
   "        top=spec.loc[ct,tfs].sort_values(ascending=False).head(4)",
   "        top=[g for g in top.index if cell_means.loc[ct,g]>0.5]   # expressed & specific",
   "        if top: masters[str(ct)]=top",
   "    masters=dict(list(masters.items())[:24])",
   "    json.dump(masters,open(f'{OUT}/celltype_masters.json','w'),indent=1)",
   "    print('Model 2 -> celltype_masters.json:',len(masters),'cell types')",
   "    for k,v in list(masters.items())[:8]: print('  ',k,'->',v)",
   "else: print('Model 2: no celltype_masters.json (builder uses validated curated masters)')"),

md("## Model 3 — Geneformer in-silico perturbation (delete)\n"
   "Tokenizes the atlas cells from Model 2, then runs Geneformer's **InSilicoPerturber** to *delete* a set of "
   "key regulators and read which genes' embeddings shift most — the **direction & reach of a knockout**. "
   "Output → `gf_perturb.json` (gene → downstream genes). GPU strongly recommended."),
code("gf_out={}",
   "TARGETS=['POLR2A','TP53','MYC','GATA4','HNF4A','SPI1','STAT1','EGFR','CTNNB1','RB1','JUN','FOXP3']",
   "try:",
   "    import torch, pickle, scipy.sparse as sp",
   "    from geneformer import TranscriptomeTokenizer, InSilicoPerturber, InSilicoPerturberStats",
   "    assert adata is not None, 'need Model-2 adata to tokenize'",
   "    # Geneformer needs Ensembl IDs in var + n_counts in obs",
   "    a=adata.copy()",
   "    a.var['ensembl_id']=a.var['feature_id'] if 'feature_id' in a.var else a.var_names",
   "    Xr=a.X; a.obs['n_counts']=np.asarray((Xr.sum(1))).ravel() if sp.issparse(Xr) else a.X.sum(1)",
   "    os.makedirs('gf_in',exist_ok=True); a.write('gf_in/atlas.h5ad')",
   "    TranscriptomeTokenizer({'cell_type':'cell_type'},nproc=4).tokenize_data('gf_in','gf_tok','atlas',file_format='h5ad')",
   "    sym2ens=dict(zip(bb['gene'],bb.get('ensembl',bb['gene'])))  # if present",
   "    ens_targets=[t for t in TARGETS]  # InSilicoPerturber maps by token; pass symbols->ensembl if available",
   "    isp=InSilicoPerturber(perturb_type='delete',genes_to_perturb='all',",
   "         model_type='Pretrained',emb_mode='cell_and_gene',cell_states_to_model=None,",
   "         max_ncells=1000,forward_batch_size=32,nproc=4)",
   "    isp.perturb_data('ctheodoris/Geneformer','gf_tok/atlas.dataset','gf_pert','pert')",
   "    st=InSilicoPerturberStats(mode='goal_state_shift')",
   "    st.get_stats('gf_pert',None,'gf_stats','stats')",
   "    dfp=pd.read_csv('gf_stats/stats.csv')",
   "    # rows: perturbed gene -> affected gene + shift; keep strongest downstream per target",
   "    col=[c for c in dfp.columns if 'Gene_name' in c or 'Gene' in c]",
   "    print('Geneformer stats columns:',list(dfp.columns)[:8])",
   "    # parse defensively depending on Geneformer version output schema",
   "    if {'Gene_name','Affected_gene_name'}.issubset(dfp.columns):",
   "        for g,grp in dfp.groupby('Gene_name'):",
   "            ds=grp.sort_values('Shift_to_goal_end' if 'Shift_to_goal_end' in grp else grp.columns[-1],ascending=False)",
   "            gf_out[str(g)]=[str(x) for x in ds['Affected_gene_name'].head(30).tolist()]",
   "    print('Model 3 -> genes with downstream sets:',len(gf_out))",
   "except Exception as e:",
   "    print('Model 3 Geneformer perturbation skipped:',repr(e)[:300])",
   "    print('  (cascade will use the measured reg+PPI graph — deterministic and auditable)')",
   "if gf_out: json.dump(gf_out,open(f'{OUT}/gf_perturb.json','w'))",
   "print('gf_perturb.json written:', bool(gf_out))"),

md("## Assemble → build → serve\n"
   "The builder now folds in whatever the three models produced (present files override the fallbacks)."),
code("!python colab/build_cell_complete.py",
   "!python colab/build_cell_app_complete.py",
   "print('cell_complete.html:', os.path.getsize(f'{OUT}/cell_complete.html')//1024,'KB')",
   "if PROJ:",
   "    import shutil",
   "    for f in ['cell_complete.html','predicted_essentiality.csv','celltype_masters.json','gf_perturb.json']:",
   "        p=f'{OUT}/{f}'",
   "        if os.path.exists(p): shutil.copy(p,f'{PROJ}/{f}')",
   "    print('copied outputs to Drive')"),
code("# render inline (Colab) or print the localhost command (local)",
   "if IN_COLAB:",
   "    from IPython.display import HTML, display",
   "    html=open(f'{OUT}/cell_complete.html').read().replace('\"','&#34;')",
   "    display(HTML(f'<iframe srcdoc=\"{html}\" width=100% height=780 style=border:0></iframe>'))",
   "else:",
   "    print('run:  python colab/serve_cell.py   ->  http://localhost:8000/cell')"),
md("## What you can now do — with all three models live\n"
   "- **Explore** → click any protein: full trafficking journey + networks; essentiality tagged *measured* vs *our model* (Model 1).\n"
   "- **cell type** dropdown → data-driven master-TF networks from the atlas (Model 2).\n"
   "- **Remove/Mutate** → cascade over the measured graph **plus Geneformer-predicted downstream genes** (Model 3, shown in purple).\n"
   "- **Metabolism / Dark genes / Infect: HIV** → reactions, the function frontier, and HIV's weak points."),
]
nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":5}
out=Path("colab/build_complete_cell.ipynb"); out.write_text(json.dumps(nb,indent=1))
print("wrote",out,"(%d cells)"%len(cells))
